<?php

namespace App;

class Channel extends Model
{
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function ($channel) {
            $channel->update([
                'slug' => $channel->name
            ]);
        });

        static::updated(function ($channel) {
            $channel->slug = $channel->name;
            $channel->save();
        });

        static::deleting(function ($channel) {
           $channel->threads()->delete();
        });
    }

    public function threads()
    {
        return $this->hasMany('App\Thread');
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function setSlugAttribute($value)
    {
        $this->setSlug($value);
    }
}
