<?php

namespace App;

class Channel extends Model
{
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::deleting(function ($channel) {
           $channel->threads()->delete();
        });
    }

    public function threads()
    {
        return $this->hasMany('App\Thread');
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }
}
