<?php

namespace App;

class Comment extends Model
{
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function ($comment) {
           $comment->update([
               'body' => clean($comment->body, 'comment_body')
           ]);
        });
    }

    public function owner()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function post()
    {
        return $this->belongsTo(Post::class, 'post_id');
    }

    // 这个评论的子评论
    public function replies()
    {
        return $this->hasMany(Comment::class, 'parent_id');
    }
}
