<?php

namespace App;

class Favorite extends Model
{
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::created(function ($favorite) {
            activity('favorite')
                ->performedOn($favorite)
                ->log('点赞了');
        });
    }

    protected $guarded = [];

    public function favorited()
    {
        return $this->morphTo();
    }
}
