<?php

namespace App;

class Topic extends Model
{
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::deleting(function ($topic) {
            $topic->posts()->delete();
        });
    }

    public function posts()
    {
        return $this->belongsToMany('App\Post', 'post_topics');
    }
}
