<?php

namespace Tests\Unit;

use Illuminate\Foundation\Testing\DatabaseMigrations;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class ThreadTest extends TestCase
{
    /**
     * A basic unit test example.
     *
     * @return void
     */
    use DatabaseMigrations;

    protected $thread;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->thread = factory('App\Thread')->create();
    }

    /*
    public function test_a_user_has_replies()
    {
        $this->assertInstanceOf('Illuminate\Database\Eloquent\Collection', $this->thread->replies);
    }

    public function test_a_thread_has_a_creator() // 话题的创建者
    {
        $this->assertInstanceOf('App\User', $this->thread->creator);
    }*/

   /* public function test_a_thread_can_add_reply()
    {
        $this->thread->addReply([
            'body' => 'Foobar',
            'user_id' => 1
        ]);

        $this->assertCount(1, $this->thread->replies);
    }*/

   /*public function test_a_thread_belongs_to_a_channel() // 测试一个话题属于一个频道
   {
        $thread = create('App\Thread');

        $this->assertInstanceOf('App\Channel', $thread->channel);
   }*/

/*   public function test_a_thread_can_make_a_string_path() // 我们期望访问 http://forum.test/threads/1 时实际是访问并且显示 http://forum.test/threads/{channel}/1
   {
       $thread = create('App\Thread');

       $this->assertEquals("/threads/{$thread->channel->slug}/{$thread->id}", $thread->path());
   }*/
}
